### ISSUE TITLE
OrientRecordLink Serialization

### ISSUE THREAD

**Issue by TropicalPenguin** [nikulukani/pyorient_native#2]
Hi,

While the CSV serializer is creating instances of OrientRecordLink, the binary serializer is returning 3-tuples of the form:

`('OrientRecordLink', <clusterID>, <recordPosition>)`

Could the binary serializer also create OrientRecordLink instances?

**Comment by nikulukani** [comment]
Thanks pointing it out. I originally did that out of haste as the speedup from the binary deserialization was critical on a project I was working on! Fixed now by 3b343f4
